; G4MEOVER Heltec ukfe_rf Empfaenger (USB Army Penetrator)
; Heltec WiFi LoRa 32 V3 = ESP32-S3 + SX1262
[env:heltec_wifi_lora_32_V3]
platform = espressif32@6.5.0
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
lib_deps =
    jgromes/RadioLib@^6.6.0
    olikraus/U8g2@^2.35.19
build_flags =
    -D UKFE_RX_BUILD
    -D ARDUINO_USB_CDC_ON_BOOT=0   ; Serial -> UART0 (CP210x/COM26), nicht natives USB-CDC
    -D ARDUINO_USB_MODE=0          ; OTG/TinyUSB -> natives USB frei fuer HID-Keyboard
